apiVersion: v1
kind: Secret
metadata:
  name: cloudshop-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: "cloudshop_user"
  DB_PASSWORD: "CloudShop@2026"
  JWT_SECRET: "cloudshop-jwt-secret-2026"
